# Dockerfile-api - UH Groupings API - also enable hot updates

# Use the pre-built base image.
FROM groupings-base-image AS build

WORKDIR /app

# Copy the start script and make it executable.
COPY start-api.sh /app/
RUN chmod +x /app/start-api.sh

CMD ["/app/start-api.sh"]
