# Dockerfile-base - UH Groupings base image builder

FROM rockylinux/rockylinux:9.4 AS build

RUN dnf -y install dnf-plugins-core epel-release && \
    dnf config-manager --set-enabled && \
    dnf -y module enable maven && \
    dnf -y install maven jq java-17-openjdk java-17-openjdk-devel && \
    dnf clean all

# Set Java 17 as the default version and set JAVA_HOME.
RUN alternatives --install /usr/bin/java java /usr/lib/jvm/java-17-openjdk/bin/java 170000 && \
    alternatives --install /usr/bin/javac javac /usr/lib/jvm/java-17-openjdk/bin/javac 170000 && \
    alternatives --set java /usr/lib/jvm/java-17-openjdk/bin/java && \
    alternatives --set javac /usr/lib/jvm/java-17-openjdk/bin/javac && \
    export JAVA_HOME=/usr/lib/jvm/java-17-openjdk && \
    export PATH=$JAVA_HOME/bin:$PATH

# Persist JAVA_HOME and PATH environment variables.
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk
ENV PATH=$JAVA_HOME/bin:$PATH
