# Dockerfile-ui - UH Groupings UI - hot update the container

# Assuming the source code will be mounted, no need to clone.
# Just prepare the environment for building the project.

# Base image for building the project.
FROM rockylinux/rockylinux:8 as build

# Install Java and Maven
RUN dnf -y module enable maven:3.6 \
    && dnf -y install maven java-17-openjdk-devel \
    && dnf clean all

WORKDIR /app

# Copy the startup script.
COPY start-ui.sh /app/start-ui.sh
RUN chmod +x /app/start-ui.sh

# Command to run the startup script.
CMD ["/app/start-ui.sh"]
