# Dockerfile-ui - UH Groupings UI - also enable hot updates

# Use the pre-built base image.
FROM groupings-base-image AS build

WORKDIR /app

# Copy the start script and make it executable.
COPY start-ui.sh /app/
RUN chmod +x /app/start-ui.sh

CMD ["/app/start-ui.sh"]